# Generated by Django 5.0.dev20230825092421 on 2023-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_reason', models.CharField(max_length=200)),
                ('task_step', models.CharField(max_length=50)),
            ],
        ),
    ]
