# Generated by Django 5.0.dev20230825092421 on 2023-08-25 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_step',
            field=models.CharField(choices=[('step_1', 'Step 1'), ('Step_2', 'Step 2'), ('step_3', 'Step 3'), ('step_4', 'Step 4')], max_length=50),
        ),
    ]
