# Generated by Django 5.0.dev20230825092421 on 2023-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_task_created_date_alter_task_task_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_step',
            field=models.CharField(choices=[('1', 'Step 1'), ('2', 'Step 2'), ('3', 'Step 3'), ('4', 'Step 4')], max_length=50),
        ),
    ]
